services:
  postgres:
    image: postgres:16-alpine
    container_name: sobatapply-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sobatapply
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  postgrest:
    image: postgrest/postgrest:latest
    container_name: sobatapply-postgrest
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/sobatapply
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    ports:
      - '3001:3000'

  redis:
    image: redis:7-alpine
    container_name: sobatapply-redis
    ports:
      - '6378:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
